### ISSUE TITLE
update for JupyterLab 1.0

### ISSUE THREAD

**Issue by das-g** [rmotr/jupyterlab-solutions#5]
Looks like a cool feature!

Can you make it available for current JupyterLab releases / versions?

Currently, when I try `jupyter labextension install @rmotr/jupyterlab-solutions` in a docker container based on [image `jupyter/minimal-notebook`](https://hub.docker.com/r/jupyter/minimal-notebook), I get the following error message:
```
An error occured.
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils
See the log file for details:  /tmp/jupyterlab-debug-c_8fr7qm.log
```
<details><summary>
content of `/tmp/jupyterlab-debug-c_8fr7qm.log` (click to expand)

</summary>

```
Node v10.13.0

> /opt/conda/bin/npm pack @rmotr/jupyterlab-solutions
npm notice 
npm notice 📦  @rmotr/jupyterlab-solutions@0.0.6
npm notice === Tarball Contents === 
npm notice 916B   package.json                          
npm notice 1.5kB  LICENSE                               
npm notice 1.5kB  README.md                             
npm notice 59B    requirements.txt                      
npm notice 556B   setup.py                              
npm notice 22.6kB yarn.lock                             
npm notice 1.4kB  jupyterlab_rmotr_solutions/__init__.py
npm notice 4.9kB  src/index.js                          
npm notice 2.7kB  style/index.css                       
npm notice === Tarball Details === 
npm notice name:          @rmotr/jupyterlab-solutions             
npm notice version:       0.0.6                                   
npm notice filename:      rmotr-jupyterlab-solutions-0.0.6.tgz    
npm notice package size:  11.1 kB                                 
npm notice unpacked size: 36.1 kB                                 
npm notice shasum:        e2a60c6a2c0b859efb0df564b196b5d775e4b12e
npm notice integrity:     sha512-wuK7JB4GowCIG[...]iEtzM2rWH2LYQ==
npm notice total files:   9                                       
npm notice 
rmotr-jupyterlab-solutions-0.0.6.tgz

Fetching URL: https://registry.npmjs.org/@rmotr%2Fjupyterlab-solutions
Fetching URL: https://registry.npmjs.org/@rmotr%2Fjupyterlab-solutions
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1416, in _install_extension
    raise ValueError(msg)

ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils

Exiting application: jupyter
```

</details>

**Comment by Easquel** [comment]
Same problem...
